# Generated by Django 3.1.1 on 2020-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Poster',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
