# Generated by Django 3.1.1 on 2020-09-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='post_likes',
            new_name='likes',
        ),
    ]
