# Generated by Django 3.1.1 on 2020-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_by',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
    ]
