# Generated by Django 3.1.1 on 2020-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201005_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
