# Generated by Django 3.1.1 on 2020-11-04 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_auto_20201005_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='like_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
