# Generated by Django 3.1.1 on 2020-11-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
    ]
