# Generated by Django 3.1.1 on 2020-11-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
