# Generated by Django 3.1.1 on 2020-12-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20201209_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='orgzer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
