# Generated by Django 3.1.1 on 2020-12-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20201223_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='Update',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
