# Generated by Django 3.1.1 on 2021-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210220_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remember_link',
            field=models.BooleanField(default=False),
        ),
    ]
