# Generated by Django 3.1.1 on 2021-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20210505_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winners',
            field=models.TextField(blank=True, default='Not Yet selected'),
        ),
    ]
