# Generated by Django 3.1.1 on 2021-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20210523_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winners',
            field=models.TextField(blank=True, default='Not Yet Decided'),
        ),
    ]
