# Generated by Django 3.1.1 on 2021-06-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20210607_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winners',
            field=models.TextField(blank=True, default='Not Yet Decided'),
        ),
    ]
