# Generated by Django 3.1.1 on 2021-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20210621_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='catagory',
            field=models.CharField(choices=[('EE', 'Elite Event'), ('ME', 'Monthly Event'), ('GE', 'General Event'), ('W', 'Workshop'), ('TT', 'Webinar/Tech Talk')], default='ME', max_length=2),
        ),
    ]
