# Generated by Django 3.1.1 on 2021-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='catagory',
            field=models.CharField(choices=[('Elite Event', 'Elite Event'), ('Monthly Event', 'Monthly Event'), ('General Event', 'General Event'), ('Workshop', 'Workshop'), ('Webinar/Tech Talk', 'Webinar/Tech Talk')], default='Monthly Event', max_length=20),
        ),
    ]
